### ISSUE TITLE
Misbehaves on optional arguments to \label command

### ISSUE THREAD

**Issue by ryanakca** [leo-colisson/proof-at-the-end#3] opened 2020-07-10 20:47 UTC
The [cleveref package](https://ctan.org/pkg/cleveref) lets users specify an optional "label" type. For example, `\label[lemma]{lem:1}` specifies that the label `lem:1` is for a lemma. Then `\cref{lem:1}` will automatically produce "lemma n" for some value of n in the text.

Unfortunately, this optional argument to the `\label` command causes proof-at-the-end to misbehave when printing theorem statements at the end. For example,
```
\begin{theoremEnd}{lemma}
  \label[lemma]{lemma:main:2}
  Let $(\sigma_n)_{n \in I}$ be a family of bijections 
\end{theoremEnd}
```
produces the following when restating the lemma at the end:
![2020-07-10-164515_511x43_scrot](https://user-images.githubusercontent.com/99287/87201573-dae85e80-c2cc-11ea-863a-5e5da5330d6c.png)

**Comment by ryanakca** [comment] 2020-07-13 16:20
I'm using texlive 2020.20200629-1 on Debian unstable. You need to specify the `restate` option to run into the bug. See the following MWE:
```
\documentclass{article}
\usepackage{amsthm}

\newtheorem{lemma}{Lemma}

\usepackage{proof-at-the-end}

\usepackage{cleveref}

\begin{document}

\begin{theoremEnd}[restate]{lemma}
  \label[lemma]{lemma:main:2}
\end{theoremEnd}

\printProofs

\end{document}
```
The file `pratenddefaultcategory.tex` has contents:
```

\prAtEndRestateii*
```
Thanks for looking into this!

**Comment by tobiasBora** [comment] 2020-07-13 18:22
Oh, indeed, sorry for missing that part. So it seems that the error is related to the `thm-restate` package, and not directly to this package, as I can easily reproduce the same error without `proof-at-the-end`:

```
\documentclass{article}
\usepackage{amsthm}
\usepackage{thm-restate}
\newtheorem{lemma}{Lemma}

\begin{document}

\begin{restatable}[Test]{lemma}{myname}
  \label[lemma]{lemma:myname}
  Hello
\end{restatable}
I can restate:

\myname*

\end{document}
```

I'm not sure where to report this bug though...

**Comment by muzimuzhi** [comment] 2020-07-13 20:45
Hi, I've added an [answer](https://tex.stackexchange.com/a/553426) to the related TeX-SX question.

In short, try this compatibility code:
```tex
\documentclass{article}
\usepackage{amsthm}
\usepackage{thm-restate}
\newtheorem{lemma}{Lemma}

\usepackage{hyperref}
\usepackage{cleveref}

\usepackage{xpatch}

%%% begin of compatibility code
\makeatletter
\@ifpackageloaded{cleveref}{
  \xpatchcmd\thmt@restatable
    {\let\label=\@gobble}
    {\let\label=\gobbled@cleveref@label}
    {}{\fail}
  
  \newcommand\gobbled@cleveref@label[2][]{}
}{}
\makeatother
%%% end of compatibility code

\begin{document}

\begin{lemma}[Lemma not restated]
  \label[lemma]{lemma:restated}
  Not an issue if not restated.
\end{lemma}

But when restated\dots
\begin{restatable}[Lemma restated]{lemma}{myname}
  \label[lemma]{lemma:myname}
  Hello
\end{restatable}
\dots it gives strange output:
\myname*

\cref{lemma:myname}
\end{document}
```

**Comment by tobiasBora** [comment] 2020-07-14 07:36
Thanks a lot ! Do you know where we could report that issue ? Meanwhile I can add this fix here, feel free to submit a PR if you like, otherwise I'll just apply the changes latter.

**Comment by muzimuzhi** [comment] 2020-07-14 14:26
@tobiasBora 
> Do you know where we could report that issue?

In my opinion this should be handled on `thmtools`' side, but I find the author of `thmtools` marked inactive on CTAN. After contacting Frank Mittelbach who updated that package in 2018 and the CTAN team, I am now the new maintainer of `thmtools` (see its [CTAN page](https://ctan.org/pkg/thmtools)). Considering the preparation work, I think a minor update to `thmtools` will be ready in one or two weeks, which will certainly contain the compatibility code with `cleveref`.

If `proof-at-the-end` wants to make it work for users with older versions of `thmtools` or even older versions of latex distribution, then a corresponding fix is still required to be added. (This seems like the aim normally wanted by a document class, since it is an upstream issue, am I right?)

**Comment by tobiasBora** [comment] 2020-07-14 14:43
Oh, that's great, thanks a lot for your reactivity.

I'm not sure to understand your comment on document class, `proof-at-the-end` is not a document class, it's just a regular package that uses `thm-restate` under the hood. Given that `proof-at-the-end` does not rely on that command, I'd say that it seems better to let `thmtools` fix the bug upstream, and keep `proof-at-the-end` as it is, for few reasons:

- anyway, if `thm-restate` is fixed and uploaded on CTAN, then on newer latex distributions the bug will not appear
- on older latex distribution, the version of `proof-at-the-end` will also be outdated, so the bug will also appear, even if I fix the bug here
- if a user is be ready to upgrade `proof-at-the-end` to avoid this bug... then why not upgrade instead `thmtools` directly?
- I'd like as much as possible to avoid to have a whole list of bug fixes, because they are hard to maintain, and could conflict with changes made by other packages...

But if somebody really thinks it's a good idea to include the fix here, I'm fine with that as well. I'll close the issue meanwhile.

**Closed by tobiasBora** 2020-07-14 14:43 UTC

**Comment by ryanakca** [comment] 2020-07-14 14:52
Thanks all for your quick responses, they saved the paper!

**Comment by muzimuzhi** [comment] 2020-07-18 19:47
> > Do you know where we could report that issue?
> 
> In my opinion this should be handled on `thmtools`' side, but I find the author of `thmtools` marked inactive on CTAN. After contacting Frank Mittelbach who updated that package in 2018 and the CTAN team, I am now the new maintainer of `thmtools` (see its [CTAN page](https://ctan.org/pkg/thmtools)). Considering the preparation work, I think a minor update to `thmtools` will be ready in one or two weeks, which will certainly contain the compatibility code with `cleveref`.

Hi, `thmtools` v69 2020-07-16 has fixed the issue, and texlive users can update now. MiKTeX users need to wait. Welcome to use and test, and `thmtools`'s new home is at https://github.com/muzimuzhi/thmtools.

**Comment by tobiasBora** [comment] 2020-07-18 19:51
Thanks a lot !
